# Generated by Django 3.0.8 on 2020-11-13 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mmeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('acount', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('uid', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_battle', models.BooleanField(default=False)),
                ('compensate', models.BooleanField(default=False)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfeatures.Mmeber')),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensate', models.BooleanField(default=False)),
                ('week', models.IntegerField(null=True)),
                ('num', models.IntegerField(null=True)),
                ('damage', models.IntegerField()),
                ('ending', models.BooleanField(default=False)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfeatures.Mmeber')),
            ],
            options={
                'db_table': 'record',
            },
        ),
    ]
