# Generated by Django 3.0.8 on 2020-11-13 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeatures', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mmeber',
            new_name='Member',
        ),
    ]
