# Generated by Django 3.0.8 on 2020-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfeatures', '0005_record_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
